on:
  push:
    branches:
      - benchmark
  schedule: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
    - cron: "0 0 * * 0" # at midnight of each sunday

name: Benchmark

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dispatch:
          - static
          - dynamic
          - fallback
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@v1
        with:
          tool: cargo-criterion
      - run: |
          pip3 install tabulate
      - run: |
          DISPATCH=${{ matrix.dispatch }} ./scripts/bench.sh --benches --plotting-backend disabled -- --warm-up-time 1 --measurement-time 1
      - name: Show results
        run: |
          COMMIT_HASH=`git rev-parse --short HEAD`
          NAME=target/simd-benches/$COMMIT_HASH-${{ matrix.dispatch }}
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "artifactPath=$NAME.md" >> $GITHUB_ENV
          cat $NAME.md
      - uses: actions/upload-artifact@v3
        with:
          name: benchmark-${{ env.COMMIT_HASH }}
          path: ${{ env.artifactPath }}

  dashboard:
    needs: benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - run: |
          COMMIT_HASH=`git rev-parse --short HEAD`
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
      - uses: actions/download-artifact@v3
        with:
          name: benchmark-${{ env.COMMIT_HASH }}
      - run: |
          ls -l
          COMMIT_HASH=${{ env.COMMIT_HASH }}
          touch result.md
          echo "## Benchmark Results" >> result.md
          for dispatch in dynamic static fallback
          do
            echo "### $dispatch" >> result.md
            echo >> result.md
            cat $COMMIT_HASH-$dispatch.md >> result.md
          done
          echo "## Environment" >> result.md
          ./scripts/print-env.sh >> result.md
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: 1330770545
          body-file: result.md
          edit-mode: replace
